# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatePlans', '0003_auto_20160819_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_kms_per_req',
            field=models.IntegerField(null=True),
        ),
    ]
