# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporatePlans', '0004_plan_free_kms_per_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kms_run', models.IntegerField()),
                ('weight', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=70)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='free_kms_per_req',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporatePlans.Plan'),
        ),
    ]
