# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatePlans', '0005_auto_20160820_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.CharField(editable=False, max_length=70),
        ),
    ]
