# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporatePlans', '0006_auto_20160822_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='kms_eqivalent_to_one_hr_for_task',
            field=models.IntegerField(null=True),
        ),
    ]
