# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporatePlans', '0007_plan_kms_eqivalent_to_one_hr_for_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='kms_eqivalent_to_one_hr_for_task',
            new_name='kms_eqivalent_per_hour',
        ),
    ]
